### ISSUE TITLE
Teemo kill message

### ISSUE THREAD

**Issue by VergilDarkSlayer** [chasem-dev/LeagueofCrafters#12]
when teemo kills you appeas: Player was killer by Teemo's posion

**Comment by chasem-dev** [comment]
Why is this a bug? THe player is killed by Teem's poison is he not?

**Comment by VergilDarkSlayer** [comment]
yes but when he kill us the message posion appears(not really a bug but a spelling error)

**Comment by chasem-dev** [comment]
Oh! Posion! I didn't see that! Thanks I will fix that now!
